server:
  port: 9527

spring:
  application:
    name: ZUUL-GATEWAY

zuul:
  prefix: /services
  ignored-services: "*"
  routes:
    system:
      path: /system/**
      serviceId: SYSTEM-SERVICE
    system:
          path: /course/**
          serviceId: COURSE-SERVICE
ribbon:
  eureka:
    enabled: true